# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: LeucothEO
subtitle: Protecting Marine Biodiversity

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: 'OdysseyMomentum/CEVEN.protect_LeucothEO/'

# Author/Organization info to be displayed in the templates
author:
  name: CEVEN.protect
  url: https://www.ceven.tech/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: About
  url: about/
  internal: true
- text: Login
  url: login/
  internal: true
- text: LeucothEO Repo
  url: https://github.com/IneffableKoD/LeucothEO
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: CEVEN.protect
  description: Momentum Repository
  url: https://github.com/OdysseyMomentum/CEVEN.protect

# Style Variables
brand_color: "#0A97D9"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
